/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.rs",
    "./index.html",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'SF Mono', 'Fira Code', 'Cascadia Code', 'monospace'],
        display: ['Instrument Serif', 'Georgia', 'Times New Roman', 'serif'],
      },
      colors: {
        dm: {
          bg:          '#09090b',
          'bg-subtle': '#0c0c0f',
          surface:     '#111113',
          'surface-hover': '#161618',
          elevated:    '#1c1c1f',
          'elevated-hover': '#222225',
          panel:       '#18181b',
          text:        '#fafafa',
          'text-secondary': '#a1a1aa',
          muted:       '#71717a',
          dim:         '#3f3f46',
          accent:      '#6366f1',
          'accent-hover': '#818cf8',
          'accent-active': '#4f46e5',
          confirmed:   '#22c55e',
          'confirmed-text': '#4ade80',
          inferred:    '#eab308',
          'inferred-text': '#facc15',
          uncertain:   '#f97316',
          'uncertain-text': '#fb923c',
          unknown:     '#ef4444',
          'unknown-text': '#f87171',
          success:     '#22c55e',
          warning:     '#eab308',
          danger:      '#ef4444',
          info:        '#6366f1',
          purple:      '#a78bfa',
        },
      },
      borderColor: {
        dm: {
          DEFAULT:    '#27272a',
          hover:      '#3f3f46',
          strong:     '#52525b',
          focus:      '#6366f1',
          accent:     'rgba(99,102,241,0.4)',
          confirmed:  'rgba(34,197,94,0.3)',
          inferred:   'rgba(234,179,8,0.3)',
          uncertain:  'rgba(249,115,22,0.3)',
          unknown:    'rgba(239,68,68,0.3)',
        },
      },
      animation: {
        'dm-fade-in':    'dm-fade-in 200ms ease-out',
        'dm-fade-in-up': 'dm-fade-in-up 350ms ease-out',
        'dm-scale-in':   'dm-scale-in 200ms ease-out',
        'dm-glow':       'dm-glow 3s ease-in-out infinite',
        'dm-glow-pulse': 'dm-glow-pulse 2s ease-in-out infinite',
        'dm-pulse':      'dm-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'dm-spin':       'dm-spin 0.8s linear infinite',
        'dm-shimmer':    'dm-shimmer 1.5s ease-in-out infinite',
        'dm-slide-down': 'dm-slide-down 150ms ease-out',
        'dm-toast-in':   'dm-toast-in 300ms ease-out',
        'dm-toast-out':  'dm-toast-out 200ms ease-in',
      },
      keyframes: {
        'dm-fade-in':     { from: { opacity: '0' }, to: { opacity: '1' } },
        'dm-fade-in-up':  { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'dm-scale-in':    { from: { opacity: '0', transform: 'scale(0.92)' }, to: { opacity: '1', transform: 'scale(1)' } },
        'dm-glow':        { '0%, 100%': { boxShadow: '0 0 8px rgba(99,102,241,0.35)' }, '50%': { boxShadow: '0 0 24px rgba(99,102,241,0.35), 0 0 48px rgba(99,102,241,0.12)' } },
        'dm-glow-pulse':  { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.6' } },
        'dm-pulse':       { '0%, 100%': { opacity: '1' }, '50%': { opacity: '0.4' } },
        'dm-spin':        { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(360deg)' } },
        'dm-shimmer':     { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        'dm-slide-down':  { from: { opacity: '0', transform: 'translateY(-8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'dm-toast-in':    { from: { opacity: '0', transform: 'translateX(100%) scale(0.95)' }, to: { opacity: '1', transform: 'translateX(0) scale(1)' } },
        'dm-toast-out':   { from: { opacity: '1', transform: 'translateX(0) scale(1)' }, to: { opacity: '0', transform: 'translateX(100%) scale(0.95)' } },
      },
    },
  },
  plugins: [],
}
